// app/page.tsx
import Home from "./Home";

type Movie = {
  adult?: boolean;
  backdrop_path?: string;
  genre_ids?: number[];
  id?: number;
  original_language?: string;
  original_title?: string;
  popularity?: number;
  poster_path?: string;
  release_date?: string;
  title?: string;
  video?: boolean;
  vote_average?: number;
  vote_count?: number;
};

const API_KEY = process.env.TMDB_key;
const BASE_URL = "https://api.themoviedb.org/3";

// Tab title and icon
export async function generateMetadata() {
  return {
    title: "Film Atlas",
    description: "Explore movies and TV Shows",
    icons: {
      icon: "/filmAtlas.ico",
    },
  };
}

// Fallback dummy movie
const fallbackMovie: Movie = {
  id: 0,
  title: "Unavailable",
  poster_path: "/image/poster.jpg", // This should be in your public/ folder
  backdrop_path: "/image/poster.jpg",
};

// Static data
const horror = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/9uP5noKg56O6OgwecxWfv152FNG.jpg",
      genre_ids: [27, 53],
      id: 1130276,
      original_language: "en",
      original_title: "Succubus",
      popularity: 2.0529,
      poster_path: "/nyGKQrctWNmhSvto8h60AhZ3iLz.jpg",
      release_date: "2024-10-06",
      title: "Succubus",
      video: false,
      vote_average: 9.391,
      vote_count: 165,
    },
    {
      adult: false,
      backdrop_path: "/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
      genre_ids: [27, 53, 9648],
      id: 539,
      original_language: "en",
      original_title: "Psycho",
      popularity: 10.5622,
      poster_path: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
      release_date: "1960-06-22",
      title: "Psycho",
      video: false,
      vote_average: 8.421,
      vote_count: 10412,
    },
    {
      adult: false,
      backdrop_path: "/jSFbnXR2vDQ0K8v0qYHt5aPCSyl.jpg",
      genre_ids: [16, 35, 10751, 27],
      id: 1150394,
      original_language: "es",
      original_title: "La Leyenda de los Chaneques",
      popularity: 4.5575,
      poster_path: "/4f9ghI3utknpeBZSAzNuIKKATOA.jpg",
      release_date: "2023-07-14",
      title: "La Leyenda de los Chaneques",
      video: false,
      vote_average: 8.387,
      vote_count: 238,
    },
    {
      adult: false,
      backdrop_path: "/qpemGrOsri13KmvkYIeU8oJ1FQD.jpg",
      genre_ids: [16, 35, 14, 12, 10751, 27],
      id: 667276,
      original_language: "es",
      original_title: "Las Leyendas: El Origen",
      popularity: 1.9819,
      poster_path: "/fR49hZdFJ6ZtRS23JW79VYmZgI7.jpg",
      release_date: "2021-02-15",
      title: "Las Leyendas: El Origen",
      video: false,
      vote_average: 8.263,
      vote_count: 260,
    },
    {
      adult: false,
      backdrop_path: "/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg",
      genre_ids: [27, 53],
      id: 694,
      original_language: "en",
      original_title: "The Shining",
      popularity: 12.0178,
      poster_path: "/xazWoLealQwEgqZ89MLZklLZD3k.jpg",
      release_date: "1980-05-23",
      title: "The Shining",
      video: false,
      vote_average: 8.211,
      vote_count: 18006,
    },
    {
      adult: false,
      backdrop_path: "/aVefEnQsfNPUrgsuMszTDt165P0.jpg",
      genre_ids: [27, 10402, 9648],
      id: 92060,
      original_language: "en",
      original_title: "Michael Jackson's Thriller",
      popularity: 1.8921,
      poster_path: "/dYHGoPMkZMVuBA4EydmDQMo1EEv.jpg",
      release_date: "1983-11-14",
      title: "Michael Jackson's Thriller",
      video: false,
      vote_average: 8.206,
      vote_count: 712,
    },
    {
      adult: false,
      backdrop_path: "/hdHIjZxq3SWFqpAz4NFhdbud0iz.jpg",
      genre_ids: [27, 878],
      id: 348,
      original_language: "en",
      original_title: "Alien",
      popularity: 15.208,
      poster_path: "/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
      release_date: "1979-05-25",
      title: "Alien",
      video: false,
      vote_average: 8.165,
      vote_count: 15374,
    },
    {
      adult: false,
      backdrop_path: "/images/poster.jpg", // Fallback image
      genre_ids: [27, 16, 14],
      id: 297610,
      original_language: "en",
      original_title: "Abraham Lincoln Vampire Hunter: The Great Calamity",
      popularity: 0.356,
      poster_path: "/9kD8bohNKE1truudhmeOtOjfNeH.jpg",
      release_date: "2012-10-23",
      title: "Abraham Lincoln Vampire Hunter: The Great Calamity",
      video: false,
      vote_average: 8.1,
      vote_count: 212,
    },
    {
      adult: false,
      backdrop_path: "/ceErqYZbHNvHjpwu4EnJna7gnCF.jpg",
      genre_ids: [16, 14, 28, 10751, 27],
      id: 494656,
      original_language: "es",
      original_title: "La leyenda del Charro Negro",
      popularity: 1.4082,
      poster_path: "/fDLJ5vIeRL68cIHlob11w2pBzH0.jpg",
      release_date: "2018-01-19",
      title: "The Legend of the Black Charro",
      video: false,
      vote_average: 8.118,
      vote_count: 178,
    },
    {
      adult: false,
      backdrop_path: "/jaO8WurWoUBE55nskqtFqPZFFaO.jpg",
      id: 1091,
      original_language: "en",
      original_title: "The Thing",
      popularity: 9.1645,
      poster_path: "/a9RjXOIIB56k2rGoL3Fk3nRHHHQ.jpg",
      release_date: "1982-06-25",
      title: "The Thing",
      video: false,
      vote_average: 8.07,
      vote_count: 7339,
    },
  ],
  total_pages: 160,
  total_results: 3199,
};

const comedy = {
  page: 1,
  results: [
    {
      id: 987032,
      year: 2024,
      title: "The Way to the Heart",
      poster_path: "/xFKzEhOhkPwMxWms1n15xLMCXa2.jpg",
      backdrop_path: "/buex9mhLHQvpAQnCU3Akdh6EbsB.jpg",
    },
    {
      id: 529414,
      year: 2018,
      title: "Franco Escamilla: por la anécdota",
      poster_path: "/iT5LzAICUgviiSY0d5461MKNSOc.jpg",
      backdrop_path: "/rxQjuLpnvve3nuDOeWSqhKTdSTj.jpg",
    },
    {
      id: 803796,
      year: 2025,
      title: "KPop Demon Hunters",
      poster_path: "/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg",
      backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
    },
    {
      id: 1181678,
      year: 2023,
      title: "¿Quieres ser mi hijo?",
      poster_path: "/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg",
      backdrop_path: "/tMH5OICumORytM9kpoo8S20KMDZ.jpg",
    },
    {
      id: 19404,
      year: 1995,
      title: "Dilwale Dulhania Le Jayenge",
      poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
      backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    },
    {
      id: 496243,
      year: 2019,
      title: "Parasite",
      poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    },
    {
      id: 680,
      year: 1994,
      title: "Pulp Fiction",
      poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
      backdrop_path: "/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg",
    },
    {
      id: 13,
      year: 1994,
      title: "Forrest Gump",
      poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
      backdrop_path: "/t0voVZuqvQ0VlM2m45rVWZO5R52.jpg",
    },
    {
      id: 938567,
      year: 2022,
      title: "Teasing Master Takagi-san: The Movie",
      poster_path: "/kGyya4tD6mDCGjfoK9lktDkLxvy.jpg",
      backdrop_path: "/t0voVZuqvQ0VlM2m45rVWZO5R52.jpg",
    },
    {
      id: 595723,
      year: 2019,
      title: "Franco Escamilla: bienvenido al mundo",
      poster_path: "/h7rzOEh1gvGRIjehKnOHcMV0YQ3.jpg",
      backdrop_path: "/wskGUSDuoqMthGykScl1ivROk8M.jpg",
    },
    {
      id: 637,
      year: 1997,
      title: "Life Is Beautiful",
      poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
      backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg",
    },
    {
      id: 40096,
      year: 2000,
      title: "A Dog's Will",
      poster_path: "/aovknfdLnFp1IiWi3yvTAg8Gm5k.jpg",
      backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
    },
    {
      id: 772071,
      year: 2022,
      title: "Cuando sea joven",
      poster_path: "/9hPa1NDUZCjGBDt0nvg4hnWis7W.jpg",
      backdrop_path: "/ejnlCzBd5pOGAYCpxC93NXSrdrz.jpg",
    },
    {
      id: 1175306,
      year: 2023,
      title: "Me vuelves loca",
      poster_path: "/pQeyfqLEDdY6x4P4Fl5r6jcstN4.jpg",
      backdrop_path: "/jR12T1oZbLCsZJwp0SKVHqSgc8X.jpg",
    },
    {
      id: 1150394,
      year: 2023,
      title: "La Leyenda de los Chaneques",
      poster_path: "/4f9ghI3utknpeBZSAzNuIKKATOA.jpg",
      backdrop_path: "/gcgKSyE2iqwfKWMDZ8TJPxeIu0P.jpg",
    },
    {
      id: 820067,
      year: 2022,
      title: "The Quintessential Quintuplets Movie",
      poster_path: "/sg7klpt1xwK1IJirBI9EHaqQwJ5.jpg",
      backdrop_path: "/yz8QL8WFD8yj0LA5zIlNOgcHvZK.jpg",
    },
    {
      id: 105,
      year: 1985,
      title: "Back to the Future",
      poster_path: "/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg",
      backdrop_path: "/pCp9kiUEqDBJQiC9o5p2jrfSJbJ.jpg",
    },
    {
      id: 937337,
      year: 2022,
      title: "What a Father!",
      poster_path: "/aZ9qQ3X8xutsWIusMFGKlvkKiyD.jpg",
      backdrop_path: "/7UCuHP7UXMwRCoFd5j56dvLnDP6.jpg",
    },
    {
      id: 914,
      year: 1940,
      title: "The Great Dictator",
      poster_path: "/nhMXB8GTdswYMCL9nepDZymJCOr.jpg",
      backdrop_path: "/c8Pi8F1FzpNebtgXcSjC9nWCdSW.jpg",
    },
    {
      id: 120301,
      year: 1953,
      title: "Dos tipos de cuidado",
      poster_path: "/86WaWg7M6M9HKEl1CWodmC5VJHQ.jpg",
      backdrop_path: "/7UCuHP7UXMwRCoFd5j56dvLnDP6.jpg",
    },
  ],
  total_pages: 382,
  total_results: 7639,
};

const action = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/gTydwZInr9ncMVFdYUzTcXtiTiT.jpg",
      genre_ids: [28],
      id: 1134055,
      original_language: "en",
      original_title: "Kill Shot",
      popularity: 4.4135,
      poster_path: "/5kCEHZnUeAZFJvE3l8K5OYjIwjj.jpg",
      release_date: "2023-08-15",
      title: "Kill Shot",
      video: false,
      vote_average: 9.093,
      vote_count: 162,
    },
    {
      adult: false,
      backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
      genre_ids: [16, 14, 28, 35, 10402],
      id: 803796,
      original_language: "en",
      original_title: "KPop Demon Hunters",
      popularity: 309.7432,
      poster_path: "/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg",
      release_date: "2025-06-20",
      title: "KPop Demon Hunters",
      video: false,
      vote_average: 8.604,
      vote_count: 304,
    },
    {
      adult: false,
      backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
      genre_ids: [18, 28, 80, 53],
      id: 155,
      original_language: "en",
      original_title: "The Dark Knight",
      popularity: 27.166,
      poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
      release_date: "2008-07-16",
      title: "The Dark Knight",
      video: false,
      vote_average: 8.521,
      vote_count: 34001,
    },
    {
      adult: false,
      backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
      genre_ids: [12, 14, 28],
      id: 122,
      original_language: "en",
      original_title: "The Lord of the Rings: The Return of the King",
      popularity: 21.3339,
      poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
      release_date: "2003-12-17",
      title: "The Lord of the Rings: The Return of the King",
      video: false,
      vote_average: 8.5,
      vote_count: 25198,
    },
    {
      adult: false,
      backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
      genre_ids: [28, 18],
      id: 346,
      original_language: "ja",
      original_title: "七人の侍",
      popularity: 8.9524,
      poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
      release_date: "1954-04-26",
      title: "Seven Samurai",
      video: false,
      vote_average: 8.455,
      vote_count: 3921,
    },
    {
      adult: false,
      backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
      genre_ids: [28, 18, 36],
      id: 14537,
      original_language: "ja",
      original_title: "切腹",
      popularity: 4.5264,
      poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
      release_date: "1962-09-15",
      title: "Harakiri",
      video: false,
      vote_average: 8.423,
      vote_count: 1091,
    },
    {
      adult: false,
      backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
      genre_ids: [12, 14, 28],
      id: 120,
      original_language: "en",
      original_title: "The Lord of the Rings: The Fellowship of the Ring",
      popularity: 27.0205,
      poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
      release_date: "2001-12-18",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      video: false,
      vote_average: 8.4,
      vote_count: 26091,
    },
    {
      adult: false,
      backdrop_path: "/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
      genre_ids: [12, 14, 28],
      id: 121,
      original_language: "en",
      original_title: "The Lord of the Rings: The Two Towers",
      popularity: 18.5729,
      poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
      release_date: "2002-12-18",
      title: "The Lord of the Rings: The Two Towers",
      video: false,
      vote_average: 8.4,
      vote_count: 22678,
    },
    {
      adult: false,
      backdrop_path: "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
      genre_ids: [16, 28, 12, 878],
      id: 324857,
      original_language: "en",
      original_title: "Spider-Man: Into the Spider-Verse",
      popularity: 16.1812,
      poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
      release_date: "2018-12-06",
      title: "Spider-Man: Into the Spider-Verse",
      video: false,
      vote_average: 8.398,
      vote_count: 16225,
    },
    {
      adult: false,
      backdrop_path: "/kgjvZgs6cV2v5bigzzzWqJ9EMGs.jpg",
      genre_ids: [12, 28, 878],
      id: 1891,
      original_language: "en",
      original_title: "The Empire Strikes Back",
      popularity: 8.098,
      poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
      release_date: "1980-05-20",
      title: "The Empire Strikes Back",
      video: false,
      vote_average: 8.396,
      vote_count: 17493,
    },
  ],
  total_pages: 213,
  total_results: 4243,
};

const popular = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
      genre_ids: [27, 9648],
      id: 574475,
      original_language: "en",
      original_title: "Final Destination Bloodlines",
      popularity: 617.5712,
      poster_path: "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
      release_date: "2025-05-14",
      title: "Final Destination Bloodlines",
      video: false,
      vote_average: 7.2,
      vote_count: 1392,
    },
    {
      adult: false,
      backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
      genre_ids: [10751, 878, 35, 12],
      id: 552524,
      original_language: "en",
      original_title: "Lilo & Stitch",
      popularity: 405.8029,
      poster_path: "/7c5VBuCbjZOk7lSfj9sMpmDIaKX.jpg",
      release_date: "2025-05-17",
      title: "Lilo & Stitch",
      video: false,
      vote_average: 7.088,
      vote_count: 748,
    },
    {
      adult: false,
      backdrop_path: "/xtnfoFs9vOLBF7Ox13mFmFUovey.jpg",
      genre_ids: [28, 12, 18],
      id: 1311844,
      original_language: "en",
      original_title: "The Twisters",
      popularity: 330.7551,
      poster_path: "/8OP3h80BzIDgmMNANVaYlQ6H4Oc.jpg",
      release_date: "2024-06-28",
      title: "The Twisters",
      video: false,
      vote_average: 5.755,
      vote_count: 47,
    },
    {
      adult: false,
      backdrop_path: "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
      genre_ids: [14, 10751, 28],
      id: 1087192,
      original_language: "en",
      original_title: "How to Train Your Dragon",
      popularity: 309.9987,
      poster_path: "/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg",
      release_date: "2025-06-06",
      title: "How to Train Your Dragon",
      video: false,
      vote_average: 7.9,
      vote_count: 475,
    },
    {
      adult: false,
      backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
      genre_ids: [16, 14, 28, 35, 10402],
      id: 803796,
      original_language: "en",
      original_title: "KPop Demon Hunters",
      popularity: 309.7432,
      poster_path: "/jfS5KEfiwsS35ieZvdUdJKkwLlZ.jpg",
      release_date: "2025-06-20",
      title: "KPop Demon Hunters",
      video: false,
      vote_average: 8.604,
      vote_count: 304,
    },
    {
      adult: false,
      backdrop_path: "/xRr7mnOJ39bZtCRmVefrm3sBxX4.jpg",
      genre_ids: [80, 53, 28],
      id: 1090007,
      original_language: "en",
      original_title: "First Shift",
      popularity: 365.1825,
      poster_path: "/ajsGI4JYaciPIe3gPgiJ3Vw5Vre.jpg",
      release_date: "2024-08-30",
      title: "First Shift",
      video: false,
      vote_average: 5.375,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: "/v47JpEeMlO0zNWCngouh0MafchU.jpg",
      genre_ids: [878, 35, 28],
      id: 605722,
      original_language: "en",
      original_title: "Distant",
      popularity: 273.9523,
      poster_path: "/czh8HOhsbBUKoKsmRmLQMCLHUev.jpg",
      release_date: "2024-07-12",
      title: "Distant",
      video: false,
      vote_average: 6.394,
      vote_count: 147,
    },
    {
      adult: false,
      backdrop_path: "/lkDYN0whyE82mcM20rwtwjbniKF.jpg",
      genre_ids: [28, 18],
      id: 911430,
      original_language: "en",
      original_title: "F1 The Movie",
      popularity: 265.3213,
      poster_path: "/6H6p82aWQFEKEuVUiZll6JxV8Ft.jpg",
      release_date: "2025-06-23",
      title: "F1 The Movie",
      video: false,
      vote_average: 7.6,
      vote_count: 265,
    },
    {
      adult: false,
      backdrop_path: "/zxjFabSJKMAvuu3acNg78nuTuCs.jpg",
      genre_ids: [28, 53, 27],
      id: 1442776,
      original_language: "zh",
      original_title: "Kuang Bao Ju Xi",
      popularity: 244.8608,
      poster_path: "/9TFaFsSXedaALXTzba349euDeoY.jpg",
      release_date: "2024-03-27",
      title: "Crazy Lizard",
      video: false,
      vote_average: 6.25,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: "/6WqqEjiycNvDLjbEClM1zCwIbDD.jpg",
      genre_ids: [27, 53, 878],
      id: 1100988,
      original_language: "en",
      original_title: "28 Years Later",
      popularity: 238.708,
      poster_path: "/361hRZoG91Nw6qXaIKuGoogQjix.jpg",
      release_date: "2025-06-18",
      title: "28 Years Later",
      video: false,
      vote_average: 7.129,
      vote_count: 388,
    },
  ].map((movie) => ({
    ...movie,
    backdrop_path: movie.backdrop_path ?? "/images/poster.jpg", // Replace null values
    poster_path: movie.poster_path ?? "/images/poster.jpg", // Replace null values
    title: movie.title ?? "Unknown Title", // Replace null values
    release_date: movie.release_date ?? "Unknown Release Date", // Replace null values
    vote_average: movie.vote_average ?? 0, // Replace null values
    vote_count: movie.vote_count ?? 0, // Replace null values
  })),
  total_pages: 51164,
  total_results: 1023276,
};

export default async function SearchResults() {
  const endpoints = {
    trending: `${BASE_URL}/trending/movie/day?api_key=${API_KEY}`,
  };

  // Fetching movies directly in server component
  const trending = await fetch(endpoints.trending)
    .then((res) => {
      if (!res.ok) throw new Error("Failed to fetch movies");
      return res.json();
    })
    .catch(() => {
      // Fallback in case of error
      return { results: [fallbackMovie] };
    });

  // Prepare movie data
  const movies = {
    trending: Array.isArray(trending.results)
      ? trending.results
      : [fallbackMovie],
    popular: popular.results || [],
    horror: horror.results || [],
    comedy: comedy.results || [],
    action: action.results || [],
  };

  return <Home movies={movies} />;
}